#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kylin-all
  namespace: kylin-quickstart
  labels:
    app: kylin
    role: all
    environment: test
    version: {YOUR_VERSION}
    hadoop.version: {YOUR_VERSION}
spec:
  serviceName: kylin-svc
  replicas: 1
  selector:
    matchLabels:
      app: kylin
      role: all
  template:
    metadata:
      labels:
        app: kylin
        role: job
    spec:
      containers:
        - name: kylin
          image: kylin-client:{YOUR_VERSION}
          imagePullPolicy: IfNotPresent
          command:
            - sh
            - -c
          args:
            - $TOOL_HOME/bootstrap.sh server;
          ports:
            - containerPort: 7070
            - containerPort: 7443
          volumeMounts:
            - name: kylin-config
              mountPath: /root/kylin/conf
            - name: kylin-logs
              mountPath: /root/kylin/logs
            - name: tomcat-logs
              mountPath: /root/kylin/tomcat/logs
            - mountPath: /etc/hadoop/conf
              name: hadoop-config
            - mountPath: /etc/hive/conf
              name: hive-config
            - mountPath: /etc/hbase/conf
              name: hbase-config
          resources:
            requests:
              memory: 4Gi
              cpu: 2
            limits:
              memory: 4Gi
              cpu: 2
          livenessProbe:
            httpGet:
              path: /kylin
              port: 7070
            initialDelaySeconds: 100
            periodSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /kylin
              port: 7070
            initialDelaySeconds: 30
            periodSeconds: 5
      volumes:
        - name: kylin-logs
          emptyDir:
            sizeLimit: 4Gi
        - name: tomcat-logs
          emptyDir:
            sizeLimit: 2Gi
        - configMap:
            name: hadoop-config
          name: hadoop-config
        - configMap:
            name: hive-config
          name: hive-config
        - configMap:
            name: hbase-config
          name: hbase-config
        - configMap:
            name: kylin-config
          name: kylin-config